### ISSUE TITLE
Criar um organization para colocar os repositórios

### ISSUE THREAD

**Issue by alexandre** [PimpAPP/pimp_my_carroca#6]
Eu acho que precisamos deixar o desenvolvimento do backend e frontend separados por repositório. Basicamente 3 repositórios (back, frontweb, frontmobile)...

Para organizar esses 3 aplicativos (e não gerar repositório duplicado como aconteceu), IMHO, seria interessante criar uma organização "pimpmycarroca" e colocar tudo lá. O que acham?

[ ]'s

**Comment by Vido** [comment]
Porque você quer criar 3 repositórios? Tem alguma vantagem?
Seria para poder plugar com CI diferentes?

Eu acho que isso não é necessário.
Criar 3 diretórios distinto já basta.

**Comment by alexandre** [comment]
Para separar o front do back nos repositórios, já que a nivel de aplicação já são separados. Os erros, issues e etc também são diferentes...

[ ]'s

**Comment by Vido** [comment]
Eu criei a organização PimpAPP
Muda o Ownership dos respositórios que você criou para PimpAPP.

**Comment by alexandre** [comment]
Ok,

Criei 3 repos dentro dessa organização.

[ ]'s

**Comment by Vido** [comment]
Ok, fica assim:
- pimp_my_carroca
  Repositório velho, e issues gerais.
- pimpapp-api
  Repo da API em flask e Dados.
- pimpapp-web
  Interface Web
- pimpapp-mobile
  Interface Mobile

**Comment by alexandre** [comment]
ok, perfeito.
